version: '3' 
services: 
  mongoCont: 
    image: mongo 
    ports:
      - "27017:27017"
    networks: 
      - mern-app
    volumes:
      - mongo-data:/data/db

  api-server:
    build: . 
    ports:
      - "3000:3000"
    networks: 
      - mern-app
    depends_on:
      - mongoCont
    environment:
      - x-rapidapi-key
      - x-rapidapi-url
      - x-rapidapi-host  

networks: 
  mern-app:
    driver: bridge

volumes: 
  mongo-data:
    driver: local